### ISSUE TITLE
Additional back end enpoints/ views on entities

### ISSUE THREAD

**Issue by jitsedesmet** [SELab-2/OSOC-6#295]
Now that we are in full api call mode we might find out we want more information when getting a certain entitiy or that we want an additional search method. If that's the case, please request it within this issue. Kasper and I will then implement that feature asap. I also assigned our API manager Thomas.

**Comment by jitsedesmet** [comment]
It became clear in #361 that a user by edition search is needed. https://github.com/SELab-2/OSOC-6/pull/361#discussion_r862470341

**Comment by andpuydt** [comment]
Can you add an endpoint to filter the students by their status?

**Comment by jitsedesmet** [comment]
Woeps, this should not have been closed?

**Comment by jitsedesmet** [comment]
@andpuydt requested an endpoint to get all skillTypes

**Comment by jitsedesmet** [comment]
We need an assignment endpoints that only gets the valid assignments.

**Comment by jitsedesmet** [comment]
Same as above but looking at it from the project. And also just remove the isSuggestion.

**Comment by KasperDemeyere** [comment]
We are done, so I'm closing this.
