### ISSUE TITLE
Broken axios

### ISSUE THREAD

**Issue by ruvmello** [SELab-2/OSOC-6#355]
Dependabot updated the axios package, but this seems to cause some issues. 
When we update the dependency, the login system seems broken. We looked in to this and think it's version 0.27.0 of axios that is causing this issue (see [changelog](https://github.com/axios/axios/blob/master/CHANGELOG.md)).

Now when we we're investigation what causes the issue, the problem seemed to come from redirects. In the changelogs, it says the follow-redirects package has been updated, so that may cause the issue.

We should look in to this later, and for now not update the axios package.

**Comment by andpuydt** [comment]
This seems to be fixed in version 0.27.2

**Comment by jitsedesmet** [comment]
Yes indeed. I will close this issue since the axios version is already merged.
