### ISSUE TITLE
Webhook not working on server

### ISSUE THREAD

**Issue by KasperDemeyere** [SELab-2/OSOC-6#371]
There seems to be a problem with the webhook receiving data from the tally form. The response we are getting is a 409 bad request.

**Comment by KasperDemeyere** [comment]
Hmm, it seems to work for me, maybe the tally webhook was not configured correctly.

**Comment by jitsedesmet** [comment]
Just so it is documented: Another option might be to match on the questions itself. This will me more work but might be an interesting option.
