### ISSUE TITLE
Favico

### ISSUE THREAD

**Issue by jitsedesmet** [SELab-2/OSOC-6#375]
We should add a favico to make the website more professional.

**Comment by ruvmello** [comment]
I tried adding this, but this doesn't seem that easy or something is wrong locally idk. As far as I can tell we need a _document.tsx file, a bit similar to _app.tsx (don't know the difference). A bit more on this is explained [here](https://nextjs.org/docs/advanced-features/custom-document).

Now some other guides for next say you can do it with _app.tsx, look [here](https://www.kindacode.com/article/how-to-add-favicon-in-next-js/). I tried a lot with both _app and _document but couldn't get it working. I just wanted to share my progress a bit as I already waisted more time on this than I would have wanted to.

**Comment by jitsedesmet** [comment]
That's unfortunate. Is it correct that you've tried both referenced resources? What favico where you using (can you link it here?)?

**Comment by ruvmello** [comment]
I did try both of them but couldn't get it to work. I generated a favicon via the svg file Lucas used in de navbar.

**Comment by jitsedesmet** [comment]
I found a way to make it work and will create the PR soon.
