### ISSUE TITLE
Registration Token bug

### ISSUE THREAD

**Issue by ruvmello** [SELab-2/OSOC-6#439]
There is a small bug when you do a post request to register a user. For some reason %3D gets added to the end of the request token in the post, this causes the request to fail and the user can't register anymore.

For example, the frontend link is the following: 
https://sel2-6.ugent.be/registration?invitationToken=b9e20fb1-e24e-4c67-8a9e-a1abb4e1576b&edition=Edition+1

The request when all the fields are filled in is going to:
https://sel2-6.ugent.be/api/registration?token=b9e20fb1-e24e-4c67-8a9e-a1abb4e1576b%3D

As you can see the end of the token isn't correctly extracted.

**Comment by jitsedesmet** [comment]
@ruvmello this was fixed right?

**Comment by ruvmello** [comment]
I think it is @andpuydt?
