### ISSUE TITLE
Add styling to the pages

### ISSUE THREAD

**Issue by thvmulle** [SELab-2/OSOC-6#457]
This issue will cover everything concerning the styling of the frontend pages.

- [x] communications
- [x] skilltypes
- [x] communictationTemplates
- [x] conflicts ~ ruvmello
- [x] projects
- [x] edit/ create project ~ruvmello
- [x] students ~thvmulle
- [x] student create ~ruvmello
- [x] assignStudents
- [x] changeEmail
- [x] changePassword
- [x] forgotPassword
- [x] login
- [x] profile ~ruvmello
- [x] registration
- [x] resetPassword
- [x] users ~ruvmello
- [x] editions ~ ruvmello
- [x] create edition ~ ruvmello
- [x] edit edition ~ruvmello

**Comment by KasperDemeyere** [comment]
Styling should be all done.
